name: top trumps mongoDB CI

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mingYi-ch/top-trumps-mongoDB@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tt_db
